name: Build and Test Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk
    steps:
      - name: Compile with Maven
        run: mvn clean compile -DSkipTests=true
  test:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk
    steps:
      - name: Test with Maven
        run: mvn clean test
  build_and_package:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk
    with:
        java-version: '17'
        distribution: temurin
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
    steps:
      - name: Package Application
        run: mvn package -DSkipTests=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-artifact
          path: target/*.jar